"""Age-banded, puzzle-friendly vocabulary for the Vocabulary Ladder series."""

GRADE_VOCABULARY = {
    "Grade School Vocabulary": """
    admire adventure amazed ancient anxious arrange arrive artist assist attention autumn balance bargain beautiful before believe belong benefit bicycle blossom border brave breeze brilliant cabin calendar careful celebrate cheerful choose clever collect color comfort compare complete confident connect curious danger decide decorate delight describe discover distance eager early earth echo educate elegant empty encourage energy engine enormous escape event explore fair family favorite feather fierce flexible float flower follow forest fortunate friendly future gentle giant glitter grateful grocery grow guard guide happy harvest healthy helpful heroic hobby honest hope hurry imagine improve include indoor invite island journey joyful jungle kindness ladder language laugh learn library listen lively lonely lucky machine magical manage manners market measure melody memory message minute miracle modern mountain museum mystery nature neighbor notice number observe ocean offer opinion ordinary organize outside palace patience peaceful perfect picnic picture planet playful please polite popular practice precious prepare present pretend proud puzzle quiet rapid ready reason recycle reflect remember rescue respect rest review river round safe sample schedule school science search season secret select sentence shadow share shelter shine should simple skill smooth solar special sparkle speech spring steady story strong student study success sudden summer surprise symbol talent thankful theater thunder tidy together travel treasure tricky trouble trust truth useful valley value village visitor wander water weekend welcome whisper winter wisdom wonder worry young zealous
    """,
    "Middle School Vocabulary": """
    ability abundant accurate activate adapt adequate advocate analyze ancient anticipate apparent approach arrange assume astonish attempt attitude authentic available avoid balance benefit brief calculate capable challenge clarify combine compare compete complex concentrate conclude conduct confirm connect consider consistent contrast convince cooperate create curious debate decrease define demonstrate describe determine develop distinguish diverse document duration effect efficient elaborate emerge emphasize enable encounter enhance enormous environment establish estimate evaluate evidence expand explain factor feature flexible focus formulate frequent function generate gradual highlight identify illustrate impact improve include indicate influence inform inspire intense interpret investigate justify language logical maintain major method modify motivate negotiate observe obtain occur participate particular perceive perform period persuade potential predict previous primary priority process promote provide publish qualify react reasonable recognize recommend reflect region regulate relevant require research respond reveal revise role route select sequence significant similar simplify solution source specific strategy structure summarize support survey symbol technique temporary theory transfer transform unique valid variety verify version visible volunteer widespread
    """,
    "High School Vocabulary": """
    abstract accelerate accommodate acknowledge acquire ambiguous analyze anticipate articulate assess assume bias catalyst coherent collaborate compelling comprehensive concede conflict contemporary contradict controversial correlate criteria crucial decline deduct define deliberate demonstrate derive diminish discriminate distinct distribute diverse empirical enhance ethical evaluate evident evolve explicit facilitate framework fundamental hypothesis illustrate imply incentive inevitable infer innovate integrate interpret justify legitimate manipulate mature maximize methodology minimize modify narrative objective paradox perspective phenomenon precise preliminary prevalent principle prioritize profound promote qualitative quantitative rational reinforce relevant reliable revise rhetoric scarce scope significant sophisticated specify stable statistic strategy subsequent substantial synthesize tentative theory transcend transform unanimous validate variable viable virtual whereas advocate anomaly arbitrary candid capacity chronology circumstance classify compatible compelling consensus constrain context criterion credible decisive defer differentiate diminish discrete dynamic empirical encounter equilibrium equivalent essential establish exclude exploitation feasible finite fluctuate formulate fragile hierarchy holistic ideology incentive incidence inevitable inhibit innovate integrity intervene intrinsic intuitive invoke isolate justify landmark literal mandate mechanism migrate mitigate mutual neutral notion objective obscure occur paradigm persistent plausible precedent prevalent priority proportion protocol pursue radical reinforce regime reluctant resilient retain reveal rhetoric scenario sector simulate sole subordinate sustainable tentative thesis trace trajectory uniform utilize volatile welfare yield
    """,
}

PUZZLE_NAMES = [
    "Everyday Words", "Words for Learning", "Words for Feelings", "Words for Actions",
    "Words for Describing", "Words for People", "Words for Places", "Words for Nature",
    "Words for Ideas", "Words for Stories", "Words for School", "Words for Growth",
    "Words for Decisions", "Words for Discovery", "Words for Communication", "Words for Success",
    "Words for Change", "Words for Challenges", "Words for Creativity", "Words for the Future",
    "Words to Know", "Words to Use", "Words to Remember", "Vocabulary Finale",
]


def words_for(topic: str) -> list[str]:
    return [word.upper() for word in GRADE_VOCABULARY[topic].split()]
